name: Release

# Push events to matching v*, i.e. v1.0, v20.15.10
on:
  push:
    tags:
    - 'v*'

jobs:
  check:
    timeout-minutes: 30
    name: Check Signed Tag
    runs-on: ubuntu-20.04
    outputs:
      stringver: ${{ steps.contentrel.outputs.stringver }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          path: src/github.com/auxon/modality-ros2

      - name: Check signature
        run: |
          RELEASE_TAG=${{ github.ref }}
          RELEASE_TAG="${RELEASE_TAG#refs/tags/}"
          TAGCHECK=$(git tag -v ${RELEASE_TAG} 2>&1 >/dev/null) ||
          echo "${TAGCHECK}" | grep -q "error" && {
              echo "::error::tag ${RELEASE_TAG} is not a signed tag. Failing release process."
              exit 1
          } || {
              echo "Tag ${RELEASE_TAG} is signed."
              exit 0
          }
        working-directory: src/github.com/auxon/modality-ros2

  package:
    name: Package
    timeout-minutes: 60
    runs-on: ubuntu-${{ matrix.ubuntu_version }}
    needs: [check]
    strategy:
      matrix:
        ubuntu_version: [20.04, 22.04]
    steps:
      - name: Print version
        run: |
          RELEASE_TAG=${{ github.ref }}
          RELEASE_TAG="${RELEASE_TAG#refs/tags/}"
          RELEASE_VERSION="${RELEASE_TAG#v}"
          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          echo "Release tag: $RELEASE_TAG"
          echo "Release version: $RELEASE_VERSION"

      - uses: actions/checkout@v3
      - uses: moonrepo/setup-rust@v0

      - name: Fetch dependencies
        working-directory: modality-ros-hook
        run: cargo fetch

      - name: Release build
        working-directory: modality-ros-hook
        run: |
          cargo build --release
          cp target/release/libmodality_ros_hook.so libmodality_ros_hook_${{matrix.ubuntu_version}}_amd64.so

      - name: Create github release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          prerelease: false
          name: Release ${{ env.RELEASE_VERSION }}
          files: |
            modality-ros-hook/libmodality_ros_hook_${{matrix.ubuntu_version}}_amd64.so
